### ISSUE TITLE
转换后还遗留原有属性单位

### ISSUE THREAD

**Issue by 1061127386** [ben-lau/postcss-pixel-to-remvw#1]
![Snipaste_2022-03-19_09-44-05](https://user-images.githubusercontent.com/59257296/159102190-a438acfe-f4d8-4f9c-afcf-40e3230d44a9.png)

可以像【postcss-px-to-viewport】 上一样加上 replace 属性，转换后直接更换属性值

**Comment by ben-lau** [comment]
我这边测了无法复现这种情况，可以给我看看你的设置和loader吗，之前有esbuild的问题会导致类似的问题

**Comment by 1061127386** [comment]
![Snipaste_2022-03-20_11-08-38](https://user-images.githubusercontent.com/59257296/159146362-fbe9148c-2924-4a36-865b-aaaf3e126373.png)
我这边用的是 vite

**Comment by ben-lau** [comment]
![image](https://user-images.githubusercontent.com/16952163/159149134-00364011-1af8-4b25-8aca-eb36fa1f7965.png)
我这边使用vite也无法复现，这块理论上跟vite也无关，你可以看看我的测试用例都不会保留的
你可以看看是否自己插入了什么插件或者配置导致的，或者提供一个最小可复现项目给我

**Comment by 1061127386** [comment]
我在上传到码云了
https://gitee.com/zhangyizhe2019/zxpsychology.git

**Comment by ben-lau** [comment]
感谢反馈，已在 2.0.4 中修复
