### ISSUE TITLE
注释方法失效（/*disable-convert-vw*/）

### ISSUE THREAD

**Issue by VOLCANO-HLC** [ben-lau/postcss-pixel-to-remvw#4]
我在使用这个插件时，发现注释方法失效了，究其原因，是插件的判断方式不全面。
我的项目，在运行当前插件前，会先使用其他的css插件，在每个css文件前面引入公共的样式；
这就导致，当该插件运行时，头部的第一个节点，已经不再是 /*disable-convert-vw*/注释了。
希望作者可以兼容一下这种场景，优化一下判断的机制

**Comment by ben-lau** [comment]
已在2.0.7修复
